import { ChartConfig, Dataset, ColumnSchema } from '../types';

export const GEOMETRIC_PALETTE = ['#4f46e5', '#6366f1', '#059669', '#d97706', '#0284c7', '#7c3aed', '#db2777'];

export function getDefaultChartsForDataset(dataset: Dataset): ChartConfig[] {
  const schema = dataset.schema;
  const numericCols = schema.filter(s => s.type === 'number');
  const stringOrDateCols = schema.filter(s => s.type === 'string' || s.type === 'date');

  const defaultX = stringOrDateCols[0]?.key || schema[0]?.key || '';
  const secondaryX = stringOrDateCols[1]?.key || defaultX;

  const num1 = numericCols[0]?.key || '';
  const num2 = numericCols[1]?.key || num1;
  const num3 = numericCols[2]?.key || num2;

  // Custom presets for known sample datasets
  if (dataset.id === 'tech-stack-lifecycle') {
    return [
      {
        id: 'chart-tech-status-distribution',
        title: 'Tech Stack Lifecycle Distribution (Active vs. Legacy vs. Lost Access)',
        type: 'donut',
        xAxisKey: 'LifecycleStatus',
        yAxisKeys: ['HealthScore'],
        aggregation: 'count',
        sortBy: 'y-desc',
        colorPalette: ['#059669', '#d97706', '#dc2626'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-tech-monthly-spend-category',
        title: 'Monthly Production Software & Infra Spend by Category ($)',
        type: 'bar',
        xAxisKey: 'Category',
        yAxisKeys: ['MonthlyCostUSD'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#06b6d4'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-tech-tools-by-owner',
        title: 'Technology Tools Portfolio by Team Owner',
        type: 'horizontal-bar',
        xAxisKey: 'TeamOwner',
        yAxisKeys: ['HealthScore'],
        aggregation: 'count',
        sortBy: 'y-desc',
        colorPalette: ['#7c3aed'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-tech-cost-vs-health',
        title: 'Cost vs. Stack Health Score by Technology Tool',
        type: 'composed',
        xAxisKey: 'TechName',
        yAxisKeys: ['MonthlyCostUSD', 'HealthScore'],
        secondaryYAxisKey: 'HealthScore',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#0284c7', '#10b981'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-tech-access-status',
        title: 'Access & Licensing Status Breakdown',
        type: 'pie',
        xAxisKey: 'AccessStatus',
        yAxisKeys: ['MonthlyCostUSD'],
        aggregation: 'count',
        sortBy: 'y-desc',
        colorPalette: ['#059669', '#3b82f6', '#f59e0b', '#8b5cf6', '#ef4444', '#64748b'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-tech-correlation',
        title: 'Tech Stack Cost & Reliability Correlation Matrix',
        type: 'correlation',
        xAxisKey: '',
        yAxisKeys: [],
        aggregation: 'none',
        colorPalette: [],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'financial-board') {
    return [
      {
        id: 'chart-fin-money-movement',
        title: 'Money Movement: Cash Inflows vs. Cost Outflows ($)',
        type: 'composed',
        xAxisKey: 'EntityName',
        yAxisKeys: ['InflowUSD', 'CostOutflowUSD'],
        secondaryYAxisKey: 'CostOutflowUSD',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#059669', '#dc2626'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-fin-cost-categories',
        title: 'Cost Breakdown by Category (Compute, SaaS & Infrastructure)',
        type: 'donut',
        xAxisKey: 'Category',
        yAxisKeys: ['CostOutflowUSD'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#e11d48', '#d97706', '#2563eb', '#7c3aed', '#059669'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-fin-trials-pipeline',
        title: 'Customer Trial Periods: Projected ARR vs. Days Remaining',
        type: 'composed',
        xAxisKey: 'CustomerAccount',
        yAxisKeys: ['SalesRevenueUSD', 'TrialDaysLeft'],
        secondaryYAxisKey: 'TrialDaysLeft',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#f59e0b'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-fin-due-dates-radar',
        title: 'Payment & Invoice Due Dates (Days Until Due)',
        type: 'horizontal-bar',
        xAxisKey: 'EntityName',
        yAxisKeys: ['DaysUntilDue'],
        aggregation: 'min',
        sortBy: 'y-asc',
        colorPalette: ['#0284c7'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-fin-net-impact-arr',
        title: 'Net Cash Flow & Annualized ARR Impact ($)',
        type: 'bar',
        xAxisKey: 'EntityName',
        yAxisKeys: ['NetCashImpact', 'ARR_Impact'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#10b981', '#6366f1'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-fin-correlation',
        title: 'Financial Flow & Due Date Correlation Grid',
        type: 'correlation',
        xAxisKey: '',
        yAxisKeys: [],
        aggregation: 'none',
        colorPalette: [],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'agentlab-telemetry') {
    return [
      {
        id: 'chart-hitl-vs-steps',
        title: 'HITL Overrides vs. Workflow Step Complexity',
        type: 'composed',
        xAxisKey: 'AgentName',
        yAxisKeys: ['HITLOverrides', 'AvgStepsPerRun'],
        secondaryYAxisKey: 'AvgStepsPerRun',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#e11d48', '#4f46e5'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-steps-scatter',
        title: 'Workflow Steps vs. Satisfaction Score',
        type: 'scatter',
        xAxisKey: 'AvgStepsPerRun',
        yAxisKeys: ['SatisfactionScore'],
        zAxisKey: 'HITLOverrides',
        aggregation: 'none',
        colorPalette: ['#059669'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-agent-runs-latency',
        title: 'Agent Executions & Latency Profile',
        type: 'composed',
        xAxisKey: 'AgentName',
        yAxisKeys: ['TotalRuns', 'AvgLatencyMs'],
        secondaryYAxisKey: 'AvgLatencyMs',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#d97706'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-tokens-stacked',
        title: 'Token Economics: Prompt vs Completion',
        type: 'stacked-bar',
        xAxisKey: 'AgentName',
        yAxisKeys: ['PromptTokens', 'CompletionTokens'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#6366f1'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-tool-calls-bar',
        title: 'Tool & Autonomous Skill Invocations',
        type: 'horizontal-bar',
        xAxisKey: 'AgentName',
        yAxisKeys: ['ToolCalls'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#059669'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-model-cost-share',
        title: 'Cloud Run Compute & API Cost by Model',
        type: 'donut',
        xAxisKey: 'Model',
        yAxisKeys: ['CostUSD'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#6366f1', '#059669', '#d97706'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-agent-correlation',
        title: 'Pearson Metric Correlation Grid',
        type: 'correlation',
        xAxisKey: '',
        yAxisKeys: [],
        aggregation: 'none',
        colorPalette: [],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'web-portal-performance') {
    return [
      {
        id: 'chart-web-conversion-vs-bounce',
        title: 'Conversion Rate vs. Bounce Rate (%)',
        type: 'composed',
        xAxisKey: 'AssetName',
        yAxisKeys: ['ConversionRate', 'BounceRate'],
        secondaryYAxisKey: 'BounceRate',
        aggregation: 'avg',
        sortBy: 'y-desc',
        colorPalette: ['#059669', '#e11d48'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-web-speed-lcp',
        title: 'Page Load Latency (ms) & Core Web Vitals LCP (sec)',
        type: 'composed',
        xAxisKey: 'AssetName',
        yAxisKeys: ['PageLoadMs', 'LCP_Seconds'],
        secondaryYAxisKey: 'LCP_Seconds',
        aggregation: 'avg',
        sortBy: 'y-asc',
        colorPalette: ['#0284c7', '#f59e0b'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-web-traffic-channels',
        title: 'Visitor Acquisition by Traffic Channel',
        type: 'donut',
        xAxisKey: 'TrafficChannel',
        yAxisKeys: ['Visitors'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#0284c7', '#10b981', '#f59e0b', '#ec4899', '#8b5cf6'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-web-portal-engagement',
        title: 'Client Portal Monthly Active Accounts & Task Conversions',
        type: 'bar',
        xAxisKey: 'AssetName',
        yAxisKeys: ['Conversions', 'PortalActiveUsers'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#10b981'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-web-session-duration',
        title: 'Average Visitor Session Dwell Time (Seconds)',
        type: 'horizontal-bar',
        xAxisKey: 'AssetName',
        yAxisKeys: ['AvgSessionDurationSec'],
        aggregation: 'avg',
        sortBy: 'y-desc',
        colorPalette: ['#7c3aed'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-web-correlation',
        title: 'Web & Client Portal Metric Correlation Grid',
        type: 'correlation',
        xAxisKey: '',
        yAxisKeys: [],
        aggregation: 'none',
        colorPalette: [],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'hubspot-crm-deals') {
    return [
      {
        id: 'chart-hubspot-stage-amount',
        title: 'HubSpot Deal Pipeline & Value by Stage',
        type: 'horizontal-bar',
        xAxisKey: 'Stage',
        yAxisKeys: ['Amount'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#f97316', '#ea580c'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-hubspot-agent-runs-vs-close',
        title: 'Associated Agent Runs vs. Days to Close',
        type: 'scatter',
        xAxisKey: 'AssociatedAgentRuns',
        yAxisKeys: ['DaysToClose'],
        zAxisKey: 'Amount',
        aggregation: 'none',
        colorPalette: ['#4f46e5'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-hubspot-pipeline-share',
        title: 'Pipeline Revenue Distribution',
        type: 'donut',
        xAxisKey: 'Pipeline',
        yAxisKeys: ['Amount'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#f97316', '#059669', '#d97706'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-hubspot-owner-deals',
        title: 'Deal Value by Sales Owner',
        type: 'bar',
        xAxisKey: 'Owner',
        yAxisKeys: ['Amount'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#059669'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'mcp-servers-telemetry') {
    return [
      {
        id: 'chart-mcp-invocations-latency',
        title: 'MCP Server Tool Invocations & Latency',
        type: 'composed',
        xAxisKey: 'ToolName',
        yAxisKeys: ['Invocations', 'AvgLatencyMs'],
        secondaryYAxisKey: 'AvgLatencyMs',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#0284c7', '#f59e0b'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-mcp-step-depth-vs-hitl',
        title: 'MCP Tool Step Depth vs. Human Overrides',
        type: 'composed',
        xAxisKey: 'ToolName',
        yAxisKeys: ['StepDepth', 'HITLOverrides'],
        secondaryYAxisKey: 'HITLOverrides',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#8b5cf6', '#e11d48'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-mcp-token-consumption',
        title: 'Token Footprint by MCP Server',
        type: 'donut',
        xAxisKey: 'McpServer',
        yAxisKeys: ['TotalTokens'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#0284c7', '#8b5cf6', '#059669', '#f59e0b', '#ec4899', '#64748b'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-mcp-success-rate',
        title: 'MCP Tool Success Reliability (%)',
        type: 'horizontal-bar',
        xAxisKey: 'ToolName',
        yAxisKeys: ['SuccessRate'],
        aggregation: 'avg',
        sortBy: 'y-asc',
        colorPalette: ['#10b981'],
        showGrid: true,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'sales-performance') {
    return [
      {
        id: 'chart-sales-trend',
        title: 'Performance Velocity Over Time',
        type: 'composed',
        xAxisKey: 'Month',
        yAxisKeys: ['Revenue', 'Profit'],
        secondaryYAxisKey: 'Profit',
        aggregation: 'sum',
        sortBy: 'none',
        colorPalette: ['#4f46e5', '#059669', '#d97706'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-region-share',
        title: 'Revenue Resource Allocation',
        type: 'donut',
        xAxisKey: 'Region',
        yAxisKeys: ['Revenue'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#6366f1', '#818cf8', '#059669', '#d97706'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-channel-units',
        title: 'Units Sold by Channel & Region',
        type: 'stacked-bar',
        xAxisKey: 'Region',
        yAxisKeys: ['UnitsSold', 'Profit'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#0284c7'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-heatmap-region-channel',
        title: 'Cross-Tabular Heatmap: Region × Channel',
        type: 'heatmap',
        xAxisKey: 'Region',
        yAxisKeys: ['Channel', 'Revenue'],
        zAxisKey: 'Revenue',
        aggregation: 'sum',
        colorPalette: ['#4f46e5'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-cac-scatter',
        title: 'CAC vs. Satisfaction Score Correlation',
        type: 'scatter',
        xAxisKey: 'CAC',
        yAxisKeys: ['SatisfactionScore'],
        zAxisKey: 'UnitsSold',
        aggregation: 'none',
        colorPalette: ['#6366f1'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-correlation-matrix',
        title: 'Statistical Pearson Correlation Grid',
        type: 'correlation',
        xAxisKey: '',
        yAxisKeys: [],
        aggregation: 'none',
        colorPalette: [],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'saas-product-tiers') {
    return [
      {
        id: 'chart-tier-arr',
        title: 'Annual Recurring Revenue (ARR) by Plan',
        type: 'bar',
        xAxisKey: 'Plan',
        yAxisKeys: ['ARR'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#6366f1', '#818cf8', '#059669', '#d97706'],
        showGrid: true,
        showLegend: false,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-users-storage',
        title: 'Active Users & Storage Consumed',
        type: 'composed',
        xAxisKey: 'Plan',
        yAxisKeys: ['ActiveUsers', 'StorageGB'],
        secondaryYAxisKey: 'StorageGB',
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#059669'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-nps-radar',
        title: 'NPS & Feature Utilization Profile',
        type: 'radar',
        xAxisKey: 'Plan',
        yAxisKeys: ['NPS', 'FeatureAdoptionPercent'],
        aggregation: 'avg',
        colorPalette: ['#4f46e5', '#0284c7'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-churn-distribution',
        title: 'Churn Rate by Subscription Tier',
        type: 'donut',
        xAxisKey: 'Plan',
        yAxisKeys: ['ChurnRatePercent'],
        aggregation: 'avg',
        sortBy: 'y-asc',
        colorPalette: ['#059669', '#d97706', '#4f46e5', '#dc2626'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  if (dataset.id === 'marketing-campaigns') {
    return [
      {
        id: 'chart-roas-ranking',
        title: 'Return on Ad Spend (ROAS) by Channel',
        type: 'horizontal-bar',
        xAxisKey: 'Channel',
        yAxisKeys: ['ROAS'],
        aggregation: 'avg',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5'],
        showGrid: true,
        showLegend: false,
        showValues: true,
        curveType: 'monotone',
      },
      {
        id: 'chart-spend-conversions-trend',
        title: 'Spend & Conversions Progression',
        type: 'composed',
        xAxisKey: 'Date',
        yAxisKeys: ['Spend', 'Conversions'],
        secondaryYAxisKey: 'Conversions',
        aggregation: 'sum',
        sortBy: 'none',
        colorPalette: ['#4f46e5', '#059669'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-ctr-cpc-scatter',
        title: 'CPC vs. CTR Efficiency Bubble Plot',
        type: 'scatter',
        xAxisKey: 'CPC',
        yAxisKeys: ['CTR'],
        zAxisKey: 'Conversions',
        aggregation: 'none',
        colorPalette: ['#6366f1'],
        showGrid: true,
        showLegend: true,
        showValues: false,
        curveType: 'monotone',
      },
      {
        id: 'chart-spend-share',
        title: 'Budget Allocation by Channel',
        type: 'donut',
        xAxisKey: 'Channel',
        yAxisKeys: ['Spend'],
        aggregation: 'sum',
        sortBy: 'y-desc',
        colorPalette: ['#4f46e5', '#6366f1', '#818cf8', '#059669', '#d97706', '#0284c7'],
        showGrid: false,
        showLegend: true,
        showValues: true,
        curveType: 'monotone',
      },
    ];
  }

  // Generic fallback generator for arbitrary user datasets
  const fallbackCharts: ChartConfig[] = [];

  if (defaultX && num1) {
    fallbackCharts.push({
      id: `gen-bar-${Date.now()}-1`,
      title: `${num1} by ${defaultX}`,
      type: 'bar',
      xAxisKey: defaultX,
      yAxisKeys: [num1],
      aggregation: 'sum',
      sortBy: 'y-desc',
      colorPalette: ['#4f46e5', '#6366f1', '#818cf8', '#059669', '#d97706'],
      showGrid: true,
      showLegend: false,
      showValues: true,
      curveType: 'monotone',
    });
  }

  if (defaultX && num1 && num2 && num1 !== num2) {
    fallbackCharts.push({
      id: `gen-trend-${Date.now()}-2`,
      title: `${num1} & ${num2} Breakdown`,
      type: 'composed',
      xAxisKey: defaultX,
      yAxisKeys: [num1, num2],
      secondaryYAxisKey: num2,
      aggregation: 'sum',
      sortBy: 'none',
      colorPalette: ['#4f46e5', '#059669'],
      showGrid: true,
      showLegend: true,
      showValues: false,
      curveType: 'monotone',
    });
  }

  if (secondaryX && num1) {
    fallbackCharts.push({
      id: `gen-donut-${Date.now()}-3`,
      title: `${num1} Distribution by ${secondaryX}`,
      type: 'donut',
      xAxisKey: secondaryX,
      yAxisKeys: [num1],
      aggregation: 'sum',
      sortBy: 'y-desc',
      colorPalette: ['#4f46e5', '#6366f1', '#818cf8', '#059669', '#d97706'],
      showGrid: false,
      showLegend: true,
      showValues: true,
      curveType: 'monotone',
    });
  }

  if (numericCols.length >= 2) {
    fallbackCharts.push({
      id: `gen-corr-${Date.now()}-4`,
      title: 'Statistical Pearson Correlation Matrix',
      type: 'correlation',
      xAxisKey: '',
      yAxisKeys: [],
      aggregation: 'none',
      colorPalette: [],
      showGrid: false,
      showLegend: true,
      showValues: true,
      curveType: 'monotone',
    });
  }

  return fallbackCharts;
}
