import { Dataset } from './types';
import { inferSchema, normalizeData } from './utils/dataProcessing';

const rawSalesData = [
  { Month: 'Jan 2025', Region: 'North America', Channel: 'Direct Sales', UnitsSold: 4200, Revenue: 126000, Profit: 37800, CAC: 42, SatisfactionScore: 4.6 },
  { Month: 'Jan 2025', Region: 'Europe', Channel: 'Direct Sales', UnitsSold: 3100, Revenue: 93000, Profit: 26040, CAC: 48, SatisfactionScore: 4.5 },
  { Month: 'Jan 2025', Region: 'Asia Pacific', Channel: 'Online', UnitsSold: 5600, Revenue: 140000, Profit: 44800, CAC: 31, SatisfactionScore: 4.8 },
  { Month: 'Jan 2025', Region: 'Latin America', Channel: 'Distributor', UnitsSold: 1800, Revenue: 45000, Profit: 11250, CAC: 36, SatisfactionScore: 4.2 },
  { Month: 'Feb 2025', Region: 'North America', Channel: 'Direct Sales', UnitsSold: 4600, Revenue: 138000, Profit: 42780, CAC: 39, SatisfactionScore: 4.7 },
  { Month: 'Feb 2025', Region: 'Europe', Channel: 'Online', UnitsSold: 3400, Revenue: 102000, Profit: 31620, CAC: 44, SatisfactionScore: 4.6 },
  { Month: 'Feb 2025', Region: 'Asia Pacific', Channel: 'Online', UnitsSold: 6100, Revenue: 152500, Profit: 50325, CAC: 29, SatisfactionScore: 4.9 },
  { Month: 'Feb 2025', Region: 'Latin America', Channel: 'Distributor', UnitsSold: 2100, Revenue: 52500, Profit: 13650, CAC: 34, SatisfactionScore: 4.3 },
  { Month: 'Mar 2025', Region: 'North America', Channel: 'Online', UnitsSold: 5200, Revenue: 161200, Profit: 51584, CAC: 35, SatisfactionScore: 4.8 },
  { Month: 'Mar 2025', Region: 'Europe', Channel: 'Direct Sales', UnitsSold: 3900, Revenue: 120900, Profit: 38688, CAC: 41, SatisfactionScore: 4.7 },
  { Month: 'Mar 2025', Region: 'Asia Pacific', Channel: 'Distributor', UnitsSold: 6800, Revenue: 176800, Profit: 60112, CAC: 27, SatisfactionScore: 4.9 },
  { Month: 'Mar 2025', Region: 'Latin America', Channel: 'Online', UnitsSold: 2500, Revenue: 65000, Profit: 17550, CAC: 32, SatisfactionScore: 4.4 },
  { Month: 'Apr 2025', Region: 'North America', Channel: 'Direct Sales', UnitsSold: 5800, Revenue: 179800, Profit: 59334, CAC: 33, SatisfactionScore: 4.8 },
  { Month: 'Apr 2025', Region: 'Europe', Channel: 'Online', UnitsSold: 4300, Revenue: 133300, Profit: 43989, CAC: 38, SatisfactionScore: 4.6 },
  { Month: 'Apr 2025', Region: 'Asia Pacific', Channel: 'Online', UnitsSold: 7400, Revenue: 199800, Profit: 69930, CAC: 25, SatisfactionScore: 5.0 },
  { Month: 'Apr 2025', Region: 'Latin America', Channel: 'Distributor', UnitsSold: 2900, Revenue: 78300, Profit: 21924, CAC: 30, SatisfactionScore: 4.5 },
  { Month: 'May 2025', Region: 'North America', Channel: 'Online', UnitsSold: 6400, Revenue: 204800, Profit: 71680, CAC: 31, SatisfactionScore: 4.9 },
  { Month: 'May 2025', Region: 'Europe', Channel: 'Direct Sales', UnitsSold: 4800, Revenue: 153600, Profit: 52224, CAC: 36, SatisfactionScore: 4.7 },
  { Month: 'May 2025', Region: 'Asia Pacific', Channel: 'Direct Sales', UnitsSold: 8100, Revenue: 226800, Profit: 81648, CAC: 24, SatisfactionScore: 5.0 },
  { Month: 'May 2025', Region: 'Latin America', Channel: 'Online', UnitsSold: 3300, Revenue: 92400, Profit: 26796, CAC: 28, SatisfactionScore: 4.6 },
  { Month: 'Jun 2025', Region: 'North America', Channel: 'Direct Sales', UnitsSold: 7100, Revenue: 234300, Profit: 84348, CAC: 29, SatisfactionScore: 4.9 },
  { Month: 'Jun 2025', Region: 'Europe', Channel: 'Online', UnitsSold: 5300, Revenue: 174900, Profit: 61215, CAC: 33, SatisfactionScore: 4.8 },
  { Month: 'Jun 2025', Region: 'Asia Pacific', Channel: 'Online', UnitsSold: 8900, Revenue: 258100, Profit: 95497, CAC: 22, SatisfactionScore: 5.0 },
  { Month: 'Jun 2025', Region: 'Latin America', Channel: 'Distributor', UnitsSold: 3800, Revenue: 110200, Profit: 33060, CAC: 26, SatisfactionScore: 4.7 },
];

const rawSaasData = [
  { Plan: 'Starter', ARR: 240000, ActiveUsers: 14200, ChurnRate: 3.4, NetRetention: 104, NPS: 48, SupportTickets: 310 },
  { Plan: 'Professional', ARR: 680000, ActiveUsers: 8500, ChurnRate: 1.8, NetRetention: 118, NPS: 62, SupportTickets: 190 },
  { Plan: 'Business', ARR: 1250000, ActiveUsers: 4900, ChurnRate: 1.1, NetRetention: 129, NPS: 71, SupportTickets: 120 },
  { Plan: 'Enterprise', ARR: 2890000, ActiveUsers: 2100, ChurnRate: 0.6, NetRetention: 142, NPS: 84, SupportTickets: 65 },
  { Plan: 'Custom Cloud', ARR: 1740000, ActiveUsers: 950, ChurnRate: 0.4, NetRetention: 155, NPS: 88, SupportTickets: 35 },
];

const rawMarketingData = [
  { Campaign: 'Search Ads (PPC)', Platform: 'Google Ads', Impressions: 850000, Clicks: 38250, Conversions: 2295, Spend: 45000, Revenue: 149175, ROI: 231 },
  { Campaign: 'Social Video Boost', Platform: 'YouTube', Impressions: 1240000, Clicks: 24800, Conversions: 992, Spend: 28000, Revenue: 64480, ROI: 130 },
  { Campaign: 'Targeted B2B Feed', Platform: 'LinkedIn', Impressions: 420000, Clicks: 14700, Conversions: 1323, Spend: 36000, Revenue: 145530, ROI: 304 },
  { Campaign: 'Community Stories', Platform: 'Instagram', Impressions: 980000, Clicks: 44100, Conversions: 1764, Spend: 31000, Revenue: 97020, ROI: 213 },
  { Campaign: 'Industry Newsletter', Platform: 'Email Substack', Impressions: 180000, Clicks: 21600, Conversions: 1944, Spend: 12000, Revenue: 116640, ROI: 872 },
  { Campaign: 'Partner Affiliate', Platform: 'Referral Net', Impressions: 310000, Clicks: 18600, Conversions: 1674, Spend: 19000, Revenue: 108810, ROI: 472 },
];

const rawAgentLabData = [
  { AgentName: 'Research & Synthesis', Model: 'gemini-2.5-flash', TotalRuns: 1420, SuccessfulRuns: 1385, FailedRuns: 35, AvgStepsPerRun: 4.8, HITLOverrides: 28, AvgLatencyMs: 940, PromptTokens: 2840000, CompletionTokens: 710000, ToolCalls: 4260, CostUSD: 3.42, SatisfactionScore: 4.85 },
  { AgentName: 'Code Generation & Refactor', Model: 'gemini-2.5-pro', TotalRuns: 980, SuccessfulRuns: 945, FailedRuns: 35, AvgStepsPerRun: 7.2, HITLOverrides: 64, AvgLatencyMs: 2450, PromptTokens: 4900000, CompletionTokens: 1470000, ToolCalls: 5880, CostUSD: 14.70, SatisfactionScore: 4.92 },
  { AgentName: 'Data ETL & Visualizer', Model: 'gemini-2.5-flash', TotalRuns: 2150, SuccessfulRuns: 2110, FailedRuns: 40, AvgStepsPerRun: 5.1, HITLOverrides: 32, AvgLatencyMs: 780, PromptTokens: 3225000, CompletionTokens: 537500, ToolCalls: 8600, CostUSD: 2.85, SatisfactionScore: 4.78 },
  { AgentName: 'Customer Support Triage', Model: 'gemini-2.0-flash', TotalRuns: 3400, SuccessfulRuns: 3340, FailedRuns: 60, AvgStepsPerRun: 2.4, HITLOverrides: 112, AvgLatencyMs: 420, PromptTokens: 1700000, CompletionTokens: 340000, ToolCalls: 1700, CostUSD: 1.15, SatisfactionScore: 4.65 },
  { AgentName: 'Compliance & Audit Inspector', Model: 'gemini-2.5-pro', TotalRuns: 620, SuccessfulRuns: 612, FailedRuns: 8, AvgStepsPerRun: 8.6, HITLOverrides: 19, AvgLatencyMs: 3100, PromptTokens: 6200000, CompletionTokens: 930000, ToolCalls: 3720, CostUSD: 16.80, SatisfactionScore: 4.95 },
  { AgentName: 'Document Parser & OCR', Model: 'gemini-2.5-flash', TotalRuns: 1850, SuccessfulRuns: 1790, FailedRuns: 60, AvgStepsPerRun: 3.9, HITLOverrides: 45, AvgLatencyMs: 1150, PromptTokens: 5550000, CompletionTokens: 740000, ToolCalls: 3700, CostUSD: 5.12, SatisfactionScore: 4.70 },
];

export const BRANDS = [
  'Uncle Robert Consulting',
  'Fundable Consulting',
  'Agent Lab',
] as const;

export type BrandName = (typeof BRANDS)[number];

export const rawHubspotDeals = [
  // Uncle Robert Consulting LLC Deals
  { DealName: 'OmniGlobal Supply Chain Executive Advisory', Brand: 'Uncle Robert Consulting', Stage: 'Closed Won', Amount: 125000, Probability: 100, Pipeline: 'Executive Consulting', Owner: 'Robert (Managing Director)', DaysToClose: 24, LeadSource: 'Direct Executive Referral', AssociatedAgentRuns: 16, HITLApproved: 1 },
  { DealName: 'Apex Capital PE Tech Audit & Diligence', Brand: 'Uncle Robert Consulting', Stage: 'Contract Sent', Amount: 85000, Probability: 90, Pipeline: 'Executive Consulting', Owner: 'Sheena Burns (Co-Founder)', DaysToClose: 18, LeadSource: 'Partner Network', AssociatedAgentRuns: 12, HITLApproved: 1 },
  { DealName: 'MedTech Group Fractional CxO Transformation', Brand: 'Uncle Robert Consulting', Stage: 'Decision Maker Buy-In', Amount: 65000, Probability: 75, Pipeline: 'Executive Consulting', Owner: 'Robert (Managing Director)', DaysToClose: 21, LeadSource: 'Inbound Advisory Request', AssociatedAgentRuns: 9, HITLApproved: 1 },

  // Fundable Consulting Deals
  { DealName: 'BioHealth Seed Syndicate $3.5M Round Raise', Brand: 'Fundable Consulting', Stage: 'Closed Won', Amount: 115000, Probability: 100, Pipeline: 'Fundraising Advisory', Owner: 'Sheena Burns (Co-Founder)', DaysToClose: 35, LeadSource: 'Venture Pitch Days', AssociatedAgentRuns: 20, HITLApproved: 1 },
  { DealName: 'Krypton AI Series A Pitch Deck Readiness', Brand: 'Fundable Consulting', Stage: 'Closed Won', Amount: 48000, Probability: 100, Pipeline: 'Fundraising Advisory', Owner: 'Robert (Managing Director)', DaysToClose: 14, LeadSource: 'Fundable Portal Inbound', AssociatedAgentRuns: 15, HITLApproved: 1 },
  { DealName: 'NextGen Fintech Investor Cohort Program', Brand: 'Fundable Consulting', Stage: 'Qualified To Buy', Amount: 36000, Probability: 60, Pipeline: 'Fundraising Advisory', Owner: 'Sheena Burns (Co-Founder)', DaysToClose: 19, LeadSource: 'AngelList Syndicate', AssociatedAgentRuns: 8, HITLApproved: 0 },
  { DealName: 'GreenEnergy Seed Stage Financial Model Review', Brand: 'Fundable Consulting', Stage: 'Contract Sent', Amount: 28000, Probability: 85, Pipeline: 'Fundraising Advisory', Owner: 'Sheena Burns (Co-Founder)', DaysToClose: 12, LeadSource: 'Fundable Portal Inbound', AssociatedAgentRuns: 6, HITLApproved: 1 },

  // Agent Lab Deals
  { DealName: 'Acme Corp Enterprise AI Tier', Brand: 'Agent Lab', Stage: 'Closed Won', Amount: 185000, Probability: 100, Pipeline: 'Direct Enterprise', Owner: 'Sarah Jenkins', DaysToClose: 42, LeadSource: 'Agent Lab Inbound', AssociatedAgentRuns: 24, HITLApproved: 1 },
  { DealName: 'TechFlow Global Workspace Expansion', Brand: 'Agent Lab', Stage: 'Decision Maker Buy-In', Amount: 94000, Probability: 75, Pipeline: 'Direct Enterprise', Owner: 'Alex Rivera', DaysToClose: 28, LeadSource: 'Product Qualified Lead', AssociatedAgentRuns: 18, HITLApproved: 1 },
  { DealName: 'Starlight Retail Multimodal Bot', Brand: 'Agent Lab', Stage: 'Contract Sent', Amount: 142000, Probability: 90, Pipeline: 'Direct Enterprise', Owner: 'Michael Chang', DaysToClose: 35, LeadSource: 'Agent Lab Inbound', AssociatedAgentRuns: 31, HITLApproved: 1 },
  { DealName: 'HealthPulse HIPAA Agent Pipeline', Brand: 'Agent Lab', Stage: 'Closed Won', Amount: 260000, Probability: 100, Pipeline: 'Healthcare Strategic', Owner: 'Sarah Jenkins', DaysToClose: 56, LeadSource: 'Outbound Executive', AssociatedAgentRuns: 45, HITLApproved: 1 },
  { DealName: 'FinVantage Auto-Reconcile Agent', Brand: 'Agent Lab', Stage: 'Presentation Scheduled', Amount: 78000, Probability: 40, Pipeline: 'Fintech Solutions', Owner: 'David Vance', DaysToClose: 14, LeadSource: 'Webinar Agent Lab', AssociatedAgentRuns: 8, HITLApproved: 0 },
  { DealName: 'Apex Logistics Document OCR & Triage', Brand: 'Agent Lab', Stage: 'Closed Won', Amount: 115000, Probability: 100, Pipeline: 'Direct Enterprise', Owner: 'Alex Rivera', DaysToClose: 31, LeadSource: 'Agent Lab Inbound', AssociatedAgentRuns: 29, HITLApproved: 1 },
  { DealName: 'EchoMedia Content Pipeline', Brand: 'Agent Lab', Stage: 'Closed Lost', Amount: 52000, Probability: 0, Pipeline: 'SMB FastTrack', Owner: 'Jessica Miller', DaysToClose: 21, LeadSource: 'Self-Serve Portal', AssociatedAgentRuns: 12, HITLApproved: 0 },
  { DealName: 'CloudScale Infrastructure Diagnostics', Brand: 'Agent Lab', Stage: 'Qualified To Buy', Amount: 88000, Probability: 50, Pipeline: 'DevOps & Tooling', Owner: 'Michael Chang', DaysToClose: 19, LeadSource: 'GitHub Marketplace', AssociatedAgentRuns: 14, HITLApproved: 1 },
];

export const rawMcpTelemetry = [
  { McpServer: 'github-mcp', ToolName: 'create_or_update_pr', Invocations: 1240, SuccessRate: 98.4, AvgLatencyMs: 820, StepDepth: 3.2, HITLOverrides: 14, TotalTokens: 1860000, Status: 'active' },
  { McpServer: 'postgres-mcp', ToolName: 'execute_analytics_query', Invocations: 3420, SuccessRate: 99.1, AvgLatencyMs: 340, StepDepth: 2.1, HITLOverrides: 8, TotalTokens: 2450000, Status: 'active' },
  { McpServer: 'hubspot-mcp', ToolName: 'sync_crm_deal_stage', Invocations: 890, SuccessRate: 97.2, AvgLatencyMs: 610, StepDepth: 2.8, HITLOverrides: 22, TotalTokens: 980000, Status: 'active' },
  { McpServer: 'slack-mcp', ToolName: 'post_incident_digest', Invocations: 2150, SuccessRate: 99.8, AvgLatencyMs: 290, StepDepth: 1.4, HITLOverrides: 5, TotalTokens: 1120000, Status: 'active' },
  { McpServer: 'brave-search-mcp', ToolName: 'deep_web_research', Invocations: 1680, SuccessRate: 96.5, AvgLatencyMs: 1450, StepDepth: 4.6, HITLOverrides: 38, TotalTokens: 4200000, Status: 'active' },
  { McpServer: 'filesystem-mcp', ToolName: 'read_and_patch_source', Invocations: 4100, SuccessRate: 98.9, AvgLatencyMs: 180, StepDepth: 5.8, HITLOverrides: 41, TotalTokens: 5900000, Status: 'active' },
];

export const rawWebPortalData = [
  // Uncle Robert Consulting LLC Web & Client Portals
  {
    AssetName: 'Uncle Robert Consulting Corporate Advisory Site',
    Brand: 'Uncle Robert Consulting',
    AssetType: 'Main Website',
    URL: 'https://unclerobertconsulting.com',
    TrafficChannel: 'Direct Executive Referral',
    Visitors: 28400,
    PageViews: 84000,
    BounceRate: 22.4,
    AvgSessionDurationSec: 260,
    ConversionRate: 14.2,
    Conversions: 4032,
    PageLoadMs: 460,
    LCP_Seconds: 1.0,
    PortalActiveUsers: 540,
    ClientSatisfactionNPS: 89,
  },
  {
    AssetName: 'Executive Strategy & Fractional Board Portal',
    Brand: 'Uncle Robert Consulting',
    AssetType: 'Client Portal',
    URL: 'https://portal.unclerobertconsulting.com',
    TrafficChannel: 'Direct Authenticated',
    Visitors: 7200,
    PageViews: 62000,
    BounceRate: 7.2,
    AvgSessionDurationSec: 490,
    ConversionRate: 88.0,
    Conversions: 6336,
    PageLoadMs: 440,
    LCP_Seconds: 0.9,
    PortalActiveUsers: 820,
    ClientSatisfactionNPS: 92,
  },

  // Fundable Consulting Web & Client Portals
  {
    AssetName: 'Fundable Consulting Startup Pitch & Diligence Hub',
    Brand: 'Fundable Consulting',
    AssetType: 'Main Website',
    URL: 'https://fundableconsulting.com',
    TrafficChannel: 'Organic & Venture Network',
    Visitors: 45200,
    PageViews: 112000,
    BounceRate: 26.5,
    AvgSessionDurationSec: 210,
    ConversionRate: 8.9,
    Conversions: 4022,
    PageLoadMs: 510,
    LCP_Seconds: 1.1,
    PortalActiveUsers: 0,
    ClientSatisfactionNPS: 83,
  },
  {
    AssetName: 'Investor DealRoom & Pitch Review Portal',
    Brand: 'Fundable Consulting',
    AssetType: 'Client Portal',
    URL: 'https://app.fundableconsulting.com',
    TrafficChannel: 'Direct Authenticated',
    Visitors: 11800,
    PageViews: 89000,
    BounceRate: 10.4,
    AvgSessionDurationSec: 460,
    ConversionRate: 82.1,
    Conversions: 9687,
    PageLoadMs: 480,
    LCP_Seconds: 1.0,
    PortalActiveUsers: 1250,
    ClientSatisfactionNPS: 87,
  },
  {
    AssetName: 'Startup Valuation & Pitch Readiness Calculator',
    Brand: 'Fundable Consulting',
    AssetType: 'Landing Page',
    URL: 'https://fundableconsulting.com/calculator',
    TrafficChannel: 'Social & Newsletter',
    Visitors: 32400,
    PageViews: 68000,
    BounceRate: 29.1,
    AvgSessionDurationSec: 290,
    ConversionRate: 12.8,
    Conversions: 4147,
    PageLoadMs: 530,
    LCP_Seconds: 1.2,
    PortalActiveUsers: 0,
    ClientSatisfactionNPS: 80,
  },

  // Agent Lab Web & Client Portals
  {
    AssetName: 'Enterprise AI Waitlist Landing Page',
    Brand: 'Agent Lab',
    AssetType: 'Landing Page',
    URL: 'https://agentlab.ai/enterprise',
    TrafficChannel: 'LinkedIn Ads',
    Visitors: 38400,
    PageViews: 52100,
    BounceRate: 28.4,
    AvgSessionDurationSec: 142,
    ConversionRate: 9.8,
    Conversions: 3763,
    PageLoadMs: 580,
    LCP_Seconds: 1.2,
    PortalActiveUsers: 0,
    ClientSatisfactionNPS: 72,
  },
  {
    AssetName: 'Agent Lab SaaS Marketing Homepage',
    Brand: 'Agent Lab',
    AssetType: 'Main Website',
    URL: 'https://agentlab.ai/',
    TrafficChannel: 'Organic Search',
    Visitors: 86500,
    PageViews: 198000,
    BounceRate: 34.2,
    AvgSessionDurationSec: 185,
    ConversionRate: 6.4,
    Conversions: 5536,
    PageLoadMs: 640,
    LCP_Seconds: 1.4,
    PortalActiveUsers: 0,
    ClientSatisfactionNPS: 75,
  },
  {
    AssetName: 'Enterprise Client Portal - Workspace Overview',
    Brand: 'Agent Lab',
    AssetType: 'Client Portal',
    URL: 'https://portal.agentlab.ai/overview',
    TrafficChannel: 'Direct Authenticated',
    Visitors: 14200,
    PageViews: 146000,
    BounceRate: 11.2,
    AvgSessionDurationSec: 420,
    ConversionRate: 84.5,
    Conversions: 11999,
    PageLoadMs: 490,
    LCP_Seconds: 1.1,
    PortalActiveUsers: 1850,
    ClientSatisfactionNPS: 84,
  },
  {
    AssetName: 'Client Portal - HITL Approvals & Run Logs',
    Brand: 'Agent Lab',
    AssetType: 'Client Portal',
    URL: 'https://portal.agentlab.ai/hitl',
    TrafficChannel: 'Direct Authenticated',
    Visitors: 8900,
    PageViews: 94000,
    BounceRate: 8.6,
    AvgSessionDurationSec: 510,
    ConversionRate: 91.2,
    Conversions: 8116,
    PageLoadMs: 520,
    LCP_Seconds: 1.3,
    PortalActiveUsers: 1420,
    ClientSatisfactionNPS: 88,
  },
  {
    AssetName: 'Interactive Agent Sandbox & Developer Docs',
    Brand: 'Agent Lab',
    AssetType: 'Docs & Resources',
    URL: 'https://docs.agentlab.ai/sandbox',
    TrafficChannel: 'Product Inbound',
    Visitors: 42300,
    PageViews: 118000,
    BounceRate: 22.8,
    AvgSessionDurationSec: 360,
    ConversionRate: 14.6,
    Conversions: 6175,
    PageLoadMs: 430,
    LCP_Seconds: 0.9,
    PortalActiveUsers: 0,
    ClientSatisfactionNPS: 81,
  },
  {
    AssetName: 'Client Portal - Billing, Usage & Invoices',
    Brand: 'Agent Lab',
    AssetType: 'Client Portal',
    URL: 'https://portal.agentlab.ai/billing',
    TrafficChannel: 'Direct Authenticated',
    Visitors: 6400,
    PageViews: 28000,
    BounceRate: 14.5,
    AvgSessionDurationSec: 210,
    ConversionRate: 76.4,
    Conversions: 4889,
    PageLoadMs: 610,
    LCP_Seconds: 1.5,
    PortalActiveUsers: 980,
    ClientSatisfactionNPS: 79,
  },
  {
    AssetName: 'Enterprise Case Studies & ROI Calculator LP',
    Brand: 'Agent Lab',
    AssetType: 'Landing Page',
    URL: 'https://agentlab.ai/case-studies',
    TrafficChannel: 'Google Search Ads',
    Visitors: 26500,
    PageViews: 41200,
    BounceRate: 31.8,
    AvgSessionDurationSec: 245,
    ConversionRate: 11.2,
    Conversions: 2968,
    PageLoadMs: 720,
    LCP_Seconds: 1.6,
    PortalActiveUsers: 0,
    ClientSatisfactionNPS: 70,
  },
  {
    AssetName: 'Client Portal - Custom Model Fine-Tuning Hub',
    Brand: 'Agent Lab',
    AssetType: 'Client Portal',
    URL: 'https://portal.agentlab.ai/models',
    TrafficChannel: 'Direct Authenticated',
    Visitors: 5100,
    PageViews: 48000,
    BounceRate: 9.4,
    AvgSessionDurationSec: 580,
    ConversionRate: 68.2,
    Conversions: 3478,
    PageLoadMs: 780,
    LCP_Seconds: 1.7,
    PortalActiveUsers: 640,
    ClientSatisfactionNPS: 86,
  },
];

export const rawFinancialData = [
  // Uncle Robert Consulting LLC (Executive Advisory & Corporate Holding)
  {
    EntityName: 'Global Supply Chain Enterprise Strategy Retainer',
    Brand: 'Uncle Robert Consulting',
    Category: 'Executive Advisory',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 125000,
    CostOutflowUSD: 0,
    NetCashImpact: 125000,
    DueDate: '2025-10-01',
    DaysUntilDue: 0,
    PaymentStatus: 'Paid / Settled',
    CustomerAccount: 'OmniGlobal Holdings',
    TrialTier: 'Quarterly Executive Retainer',
    TrialPeriodDays: 90,
    TrialDaysLeft: 0,
    TrialStatus: 'Active Retainer ($125k)',
    TrialConversionProb: 100,
    SalesRevenueUSD: 125000,
    ARR_Impact: 500000,
    ContractType: 'Executive Retainer',
  },
  {
    EntityName: 'Private Equity M&A Due Diligence & Tech Audit',
    Brand: 'Uncle Robert Consulting',
    Category: 'Executive Advisory',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 85000,
    CostOutflowUSD: 0,
    NetCashImpact: 85000,
    DueDate: '2025-10-04',
    DaysUntilDue: 3,
    PaymentStatus: 'Invoice Pending',
    CustomerAccount: 'Apex Capital Partners',
    TrialTier: 'Project Diligence Retainer',
    TrialPeriodDays: 30,
    TrialDaysLeft: 0,
    TrialStatus: 'Project Deliverable Due',
    TrialConversionProb: 100,
    SalesRevenueUSD: 85000,
    ARR_Impact: 85000,
    ContractType: 'Project Advisory',
  },
  {
    EntityName: 'Fractional CxO Transformation & Board Advisory',
    Brand: 'Uncle Robert Consulting',
    Category: 'Executive Advisory',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 65000,
    CostOutflowUSD: 0,
    NetCashImpact: 65000,
    DueDate: '2025-10-10',
    DaysUntilDue: 9,
    PaymentStatus: 'Scheduled Inflow',
    CustomerAccount: 'MedTech Group',
    TrialTier: 'Monthly Advisory Retainer',
    TrialPeriodDays: 30,
    TrialDaysLeft: 0,
    TrialStatus: 'Active Retainer ($65k/mo)',
    TrialConversionProb: 100,
    SalesRevenueUSD: 65000,
    ARR_Impact: 780000,
    ContractType: 'Monthly Advisory',
  },
  {
    EntityName: 'Corporate Legal, Entity Structuring & Tax Counsel',
    Brand: 'Uncle Robert Consulting',
    Category: 'Corporate & Legal Overhead',
    TransactionType: 'Outflow (Operations)',
    InflowUSD: 0,
    CostOutflowUSD: 7500,
    NetCashImpact: -7500,
    DueDate: '2025-10-15',
    DaysUntilDue: 14,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Holding Company Overhead',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -90000,
    ContractType: 'Monthly Retainer',
  },

  // Fundable Consulting (Startup Fundraising & Pitch Readiness)
  {
    EntityName: 'BioHealth Seed Round Syndicate Deal Success Fee',
    Brand: 'Fundable Consulting',
    Category: 'Fundraising Success Fees',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 115000,
    CostOutflowUSD: 0,
    NetCashImpact: 115000,
    DueDate: '2025-10-02',
    DaysUntilDue: 1,
    PaymentStatus: 'Paid / Settled',
    CustomerAccount: 'BioHealth Technologies',
    TrialTier: 'Fundraising Success Escrow',
    TrialPeriodDays: 60,
    TrialDaysLeft: 0,
    TrialStatus: 'Round Closed ($3.5M)',
    TrialConversionProb: 100,
    SalesRevenueUSD: 115000,
    ARR_Impact: 115000,
    ContractType: 'Deal Success Fee',
  },
  {
    EntityName: 'Series A Venture Pitch Deck & Financial Modeling',
    Brand: 'Fundable Consulting',
    Category: 'Fundraising Advisory',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 48000,
    CostOutflowUSD: 0,
    NetCashImpact: 48000,
    DueDate: '2025-10-06',
    DaysUntilDue: 5,
    PaymentStatus: 'Invoice Pending',
    CustomerAccount: 'Krypton AI Systems',
    TrialTier: 'Pitch Readiness Sprint',
    TrialPeriodDays: 21,
    TrialDaysLeft: 0,
    TrialStatus: 'Final Sprint Review',
    TrialConversionProb: 100,
    SalesRevenueUSD: 48000,
    ARR_Impact: 48000,
    ContractType: 'Fixed Advisory Sprint',
  },
  {
    EntityName: 'Founder Pitch Deck Cohort Accelerator Intake',
    Brand: 'Fundable Consulting',
    Category: 'Cohort Programs',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 36000,
    CostOutflowUSD: 0,
    NetCashImpact: 36000,
    DueDate: '2025-10-12',
    DaysUntilDue: 11,
    PaymentStatus: 'Paid / Settled',
    CustomerAccount: 'Fall Founder Cohort (12 Founders)',
    TrialTier: 'Cohort Membership',
    TrialPeriodDays: 45,
    TrialDaysLeft: 0,
    TrialStatus: 'Active Cohort',
    TrialConversionProb: 100,
    SalesRevenueUSD: 36000,
    ARR_Impact: 144000,
    ContractType: 'Quarterly Cohort',
  },
  {
    EntityName: 'BioHealth Seed Advisory 14-Day Diligence Trial',
    Brand: 'Fundable Consulting',
    Category: 'Active Customer Trials',
    TransactionType: 'Trial Period (Pipeline)',
    InflowUSD: 0,
    CostOutflowUSD: 350,
    NetCashImpact: -350,
    DueDate: '2025-10-07',
    DaysUntilDue: 6,
    PaymentStatus: 'Active Trial',
    CustomerAccount: 'BioHealth Technologies',
    TrialTier: 'Fundable Intake Pilot (14-Day)',
    TrialPeriodDays: 14,
    TrialDaysLeft: 6,
    TrialStatus: 'Active (6d left)',
    TrialConversionProb: 90,
    SalesRevenueUSD: 85000,
    ARR_Impact: 85000,
    ContractType: 'Trial - Projected Success Fee',
  },
  {
    EntityName: 'PitchBook & Crunchbase Pro Venture Intelligence',
    Brand: 'Fundable Consulting',
    Category: 'SaaS & Software Subscriptions',
    TransactionType: 'Outflow (SaaS Sub)',
    InflowUSD: 0,
    CostOutflowUSD: 2400,
    NetCashImpact: -2400,
    DueDate: '2025-10-18',
    DaysUntilDue: 17,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Venture Research Suite',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -28800,
    ContractType: 'Annual SaaS (Monthly Bill)',
  },

  // Agent Lab (AI Systems, Cloud Run, API Models & Enterprise Licenses)
  {
    EntityName: 'Acme Corp Annual Enterprise Contract',
    Brand: 'Agent Lab',
    Category: 'Enterprise Sales',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 185000,
    CostOutflowUSD: 0,
    NetCashImpact: 185000,
    DueDate: '2025-10-01',
    DaysUntilDue: 0,
    PaymentStatus: 'Paid / Settled',
    CustomerAccount: 'Acme Corp',
    TrialTier: 'Converted from Pilot',
    TrialPeriodDays: 30,
    TrialDaysLeft: 0,
    TrialStatus: 'Converted to Annual ($185k)',
    TrialConversionProb: 100,
    SalesRevenueUSD: 185000,
    ARR_Impact: 185000,
    ContractType: 'Annual Enterprise',
  },
  {
    EntityName: 'Google Cloud Platform & Cloud Run Cluster',
    Category: 'Cloud & AI Compute Cost',
    TransactionType: 'Outflow (Infra Cost)',
    InflowUSD: 0,
    CostOutflowUSD: 14200,
    NetCashImpact: -14200,
    DueDate: '2025-10-05',
    DaysUntilDue: 4,
    PaymentStatus: 'Due in 4 Days',
    CustomerAccount: 'Internal Operations',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -170400,
    ContractType: 'Monthly Infrastructure',
  },
  {
    EntityName: 'Anthropic Claude 3.7 Sonnet Inference Fleet',
    Category: 'Cloud & AI Compute Cost',
    TransactionType: 'Outflow (LLM Tokens)',
    InflowUSD: 0,
    CostOutflowUSD: 18900,
    NetCashImpact: -18900,
    DueDate: '2025-10-08',
    DaysUntilDue: 7,
    PaymentStatus: 'Due in 7 Days',
    CustomerAccount: 'Internal Operations',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -226800,
    ContractType: 'Usage Invoicing',
  },
  {
    EntityName: 'FinTech Global Scale Multi-Agent License',
    Category: 'Enterprise Sales',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 94000,
    CostOutflowUSD: 0,
    NetCashImpact: 94000,
    DueDate: '2025-10-03',
    DaysUntilDue: 2,
    PaymentStatus: 'Invoice Pending',
    CustomerAccount: 'FinTech Global',
    TrialTier: 'Converted from Pilot',
    TrialPeriodDays: 14,
    TrialDaysLeft: 0,
    TrialStatus: 'Converted to Annual ($94k)',
    TrialConversionProb: 100,
    SalesRevenueUSD: 94000,
    ARR_Impact: 94000,
    ContractType: 'Annual Enterprise',
  },
  {
    EntityName: 'OpenAI Batch Embedding & Vector Fleet',
    Category: 'Cloud & AI Compute Cost',
    TransactionType: 'Outflow (LLM Tokens)',
    InflowUSD: 0,
    CostOutflowUSD: 8600,
    NetCashImpact: -8600,
    DueDate: '2025-10-12',
    DaysUntilDue: 11,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Internal Operations',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -103200,
    ContractType: 'Usage Invoicing',
  },
  {
    EntityName: 'Synthetix AI Enterprise 14-Day Pilot',
    Category: 'Active Customer Trials',
    TransactionType: 'Trial Period (Pipeline)',
    InflowUSD: 0,
    CostOutflowUSD: 650,
    NetCashImpact: -650,
    DueDate: '2025-10-04',
    DaysUntilDue: 3,
    PaymentStatus: 'Active Trial',
    CustomerAccount: 'Synthetix AI',
    TrialTier: 'Enterprise AI Pilot (14-Day)',
    TrialPeriodDays: 14,
    TrialDaysLeft: 3,
    TrialStatus: 'Expiring in 3 Days',
    TrialConversionProb: 88,
    SalesRevenueUSD: 120000,
    ARR_Impact: 120000,
    ContractType: 'Trial - Projected Annual',
  },
  {
    EntityName: 'HubSpot CRM Enterprise & Marketing Suite',
    Category: 'SaaS & Software Subscriptions',
    TransactionType: 'Outflow (SaaS Sub)',
    InflowUSD: 0,
    CostOutflowUSD: 3600,
    NetCashImpact: -3600,
    DueDate: '2025-10-15',
    DaysUntilDue: 14,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Sales & Go-to-Market',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -43200,
    ContractType: 'Annual SaaS (Monthly Bill)',
  },
  {
    EntityName: 'NovaCorp Logistics Multi-Agent Sandbox',
    Category: 'Active Customer Trials',
    TransactionType: 'Trial Period (Pipeline)',
    InflowUSD: 0,
    CostOutflowUSD: 420,
    NetCashImpact: -420,
    DueDate: '2025-10-07',
    DaysUntilDue: 6,
    PaymentStatus: 'Active Trial',
    CustomerAccount: 'NovaCorp Logistics',
    TrialTier: 'Growth Plan Trial (21-Day)',
    TrialPeriodDays: 21,
    TrialDaysLeft: 6,
    TrialStatus: 'Active (6d left)',
    TrialConversionProb: 75,
    SalesRevenueUSD: 68000,
    ARR_Impact: 68000,
    ContractType: 'Trial - Projected Annual',
  },
  {
    EntityName: 'Stripe SaaS Recurring Subscriptions Payout',
    Category: 'Self-Serve Subscriptions',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 64200,
    CostOutflowUSD: 0,
    NetCashImpact: 64200,
    DueDate: '2025-10-02',
    DaysUntilDue: 1,
    PaymentStatus: 'Paid / Settled',
    CustomerAccount: 'Platform Self-Serve',
    TrialTier: 'Paid Production',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'Paid Production Tier',
    TrialConversionProb: 100,
    SalesRevenueUSD: 64200,
    ARR_Impact: 770400,
    ContractType: 'Monthly Recurring',
  },
  {
    EntityName: 'Datadog APM, Profiling & Distributed Tracing',
    Category: 'SaaS & Software Subscriptions',
    TransactionType: 'Outflow (SaaS Sub)',
    InflowUSD: 0,
    CostOutflowUSD: 2800,
    NetCashImpact: -2800,
    DueDate: '2025-10-18',
    DaysUntilDue: 17,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Internal Operations',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -33600,
    ContractType: 'Monthly Usage SaaS',
  },
  {
    EntityName: 'Vanguard Health Autonomous HITL Pilot',
    Category: 'Active Customer Trials',
    TransactionType: 'Trial Period (Pipeline)',
    InflowUSD: 0,
    CostOutflowUSD: 890,
    NetCashImpact: -890,
    DueDate: '2025-10-09',
    DaysUntilDue: 8,
    PaymentStatus: 'Active Trial',
    CustomerAccount: 'Vanguard Health',
    TrialTier: 'Enterprise AI Pilot (30-Day)',
    TrialPeriodDays: 30,
    TrialDaysLeft: 8,
    TrialStatus: 'Active (8d left)',
    TrialConversionProb: 92,
    SalesRevenueUSD: 210000,
    ARR_Impact: 210000,
    ContractType: 'Trial - Projected Annual',
  },
  {
    EntityName: 'GitHub Enterprise & Copilot Workspace Seats',
    Category: 'SaaS & Software Subscriptions',
    TransactionType: 'Outflow (SaaS Sub)',
    InflowUSD: 0,
    CostOutflowUSD: 1950,
    NetCashImpact: -1950,
    DueDate: '2025-10-22',
    DaysUntilDue: 21,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Engineering Fleet',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -23400,
    ContractType: 'Monthly SaaS',
  },
  {
    EntityName: 'AWS S3 Cold Storage & CloudFront Backups',
    Category: 'Cloud & AI Compute Cost',
    TransactionType: 'Outflow (Infra Cost)',
    InflowUSD: 0,
    CostOutflowUSD: 1120,
    NetCashImpact: -1120,
    DueDate: '2025-10-25',
    DaysUntilDue: 24,
    PaymentStatus: 'Scheduled Autopay',
    CustomerAccount: 'Internal Operations',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -13440,
    ContractType: 'Monthly Infrastructure',
  },
  {
    EntityName: 'Brave Search & Tavily MCP Query Token Packs',
    Category: 'Cloud & AI Compute Cost',
    TransactionType: 'Outflow (LLM Tokens)',
    InflowUSD: 0,
    CostOutflowUSD: 850,
    NetCashImpact: -850,
    DueDate: '2025-10-10',
    DaysUntilDue: 9,
    PaymentStatus: 'Due in 9 Days',
    CustomerAccount: 'Agent Research Fleet',
    TrialTier: 'N/A - Vendor Cost',
    TrialPeriodDays: 0,
    TrialDaysLeft: 0,
    TrialStatus: 'N/A - Vendor Cost',
    TrialConversionProb: 0,
    SalesRevenueUSD: 0,
    ARR_Impact: -10200,
    ContractType: 'Usage Invoicing',
  },
  {
    EntityName: 'Meridian Care Management Expansion Deal',
    Category: 'Enterprise Sales',
    TransactionType: 'Inflow (Sales)',
    InflowUSD: 115000,
    CostOutflowUSD: 0,
    NetCashImpact: 115000,
    DueDate: '2025-10-14',
    DaysUntilDue: 13,
    PaymentStatus: 'Invoice Sent',
    CustomerAccount: 'Meridian Care',
    TrialTier: 'Converted from Pilot',
    TrialPeriodDays: 14,
    TrialDaysLeft: 0,
    TrialStatus: 'Converted to Annual ($115k)',
    TrialConversionProb: 100,
    SalesRevenueUSD: 115000,
    ARR_Impact: 115000,
    ContractType: 'Annual Enterprise',
  },
  {
    EntityName: 'AeroDynamics Aerospace Sandbox Pilot',
    Category: 'Active Customer Trials',
    TransactionType: 'Trial Period (Pipeline)',
    InflowUSD: 0,
    CostOutflowUSD: 520,
    NetCashImpact: -520,
    DueDate: '2025-10-06',
    DaysUntilDue: 5,
    PaymentStatus: 'Active Trial',
    CustomerAccount: 'AeroDynamics Tech',
    TrialTier: 'Enterprise AI Pilot (14-Day)',
    TrialPeriodDays: 14,
    TrialDaysLeft: 5,
    TrialStatus: 'Active (5d left)',
    TrialConversionProb: 80,
    SalesRevenueUSD: 145000,
    ARR_Impact: 145000,
    ContractType: 'Trial - Projected Annual',
  },
];

export const rawTechStackData: Record<string, any>[] = [
  // --- 1. ACTIVE IN PRODUCTION ---
  {
    TechName: 'Google Cloud Run',
    Category: 'Cloud & Compute Infrastructure',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Primary container execution engine for Agent Lab microservices, event workers, and web ingress routing.',
    AccessStatus: 'Active Enterprise SSO',
    WhyLostOrDeprecated: 'Current standard: Zero-to-one auto-scaling with predictable per-request billing and instant rollback capabilities.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 1420,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'Verified & Monitored (GCP IAM)',
    AdoptionQuarter: '2024-Q1',
    DeprecationQuarter: 'Active',
    HealthScore: 98,
  },
  {
    TechName: 'Gemini 2.5 Pro & Flash',
    Category: 'AI & LLM Orchestration',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Core generative AI reasoning, complex multi-step code generation, multimodal analysis, and fast real-time synthesis.',
    AccessStatus: 'Paid Monthly Subscription (Google GenAI)',
    WhyLostOrDeprecated: 'Current standard: 1M+ token context window, lowest latency per token, and native structured schema extraction.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 2450,
    TeamOwner: 'AI Engineering',
    CredentialsState: 'Verified & Monitored (Server-side API Secrets)',
    AdoptionQuarter: '2024-Q2',
    DeprecationQuarter: 'Active',
    HealthScore: 99,
  },
  {
    TechName: 'PostgreSQL & pgvector (Cloud SQL)',
    Category: 'Databases & Vector Storage',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'System-of-record transactional database, customer telemetry logs, tenant configuration, and vector similarity embeddings.',
    AccessStatus: 'Active Enterprise SSO',
    WhyLostOrDeprecated: 'Current standard: Replaced standalone vector DBs by consolidating relational tables and vectors inside single ACID compliant database.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 780,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'Verified & Monitored (IAM Auth & SSL)',
    AdoptionQuarter: '2024-Q1',
    DeprecationQuarter: 'Active',
    HealthScore: 96,
  },
  {
    TechName: 'Model Context Protocol (MCP)',
    Category: 'Integrations & Automation',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Standardized client-server bridge connecting Agent Lab assistants directly to PostgreSQL, GitHub, Slack, and internal tools.',
    AccessStatus: 'Open Source / Self-Hosted',
    WhyLostOrDeprecated: 'Current standard: Decouples LLM tool interfaces from proprietary vendor SDKs, allowing zero-friction agent tool expansion.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 0,
    TeamOwner: 'AI Engineering',
    CredentialsState: 'Verified & Monitored (Self-hosted daemon)',
    AdoptionQuarter: '2024-Q4',
    DeprecationQuarter: 'Active',
    HealthScore: 95,
  },
  {
    TechName: 'Vite + React 18 + Tailwind CSS',
    Category: 'Developer Tooling & CI/CD',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Primary web application framework, internal analytics dashboards, client portals, and responsive interactive visualization.',
    AccessStatus: 'Open Source Standard',
    WhyLostOrDeprecated: 'Current standard: Sub-second hot module compilation, lightweight bundle size, and comprehensive responsive UI design system.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 0,
    TeamOwner: 'Product Eng',
    CredentialsState: 'Verified & Monitored (GitHub Repos)',
    AdoptionQuarter: '2023-Q4',
    DeprecationQuarter: 'Active',
    HealthScore: 97,
  },
  {
    TechName: 'Stripe Billing & Connect',
    Category: 'Customer & Revenue Ops',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'SaaS recurring subscription billing, customer invoicing, enterprise trial payment methods, and automated webhook reconciliation.',
    AccessStatus: 'Paid Production Tier (Transaction %)',
    WhyLostOrDeprecated: 'Current standard: Automated PCI DSS compliance, global payment methods, and seamless customer portal integration.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 1650,
    TeamOwner: 'Founders / Finance',
    CredentialsState: 'Verified & Monitored (Restricted API Keys)',
    AdoptionQuarter: '2023-Q2',
    DeprecationQuarter: 'Active',
    HealthScore: 99,
  },
  {
    TechName: 'HubSpot CRM (API v3)',
    Category: 'Customer & Revenue Ops',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Enterprise sales pipeline, deal stage synchronization, qualified lead triage, and direct Agent Lab run associations.',
    AccessStatus: 'Paid Monthly Subscription (Professional)',
    WhyLostOrDeprecated: 'Current standard: Centralized account executive workflows, automated deal tracking, and bidirectional webhook sync.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 1200,
    TeamOwner: 'Growth & Sales',
    CredentialsState: 'Verified & Monitored (OAuth 2.0 App)',
    AdoptionQuarter: '2023-Q4',
    DeprecationQuarter: 'Active',
    HealthScore: 94,
  },
  {
    TechName: 'GitHub Actions & Container Registry',
    Category: 'Developer Tooling & CI/CD',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Automated CI/CD test runners, Docker container image multi-arch compilation, linting, and automated Cloud Run deployment.',
    AccessStatus: 'Active Enterprise SSO',
    WhyLostOrDeprecated: 'Current standard: Native source code integration, encrypted repository secrets, and fast branch build previews.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 210,
    TeamOwner: 'DevOps & Security',
    CredentialsState: 'Verified & Monitored (OIDC Workload Identity)',
    AdoptionQuarter: '2023-Q3',
    DeprecationQuarter: 'Active',
    HealthScore: 98,
  },
  {
    TechName: 'Google Cloud Logging & Error Reporting',
    Category: 'Monitoring & Observability',
    LifecycleStatus: 'Active (In Production)',
    CurrentOrPastWorkload: 'Centralized streaming application logs, crash stack-trace aggregation, and latency alert thresholds across all containers.',
    AccessStatus: 'Active Enterprise SSO',
    WhyLostOrDeprecated: 'Current standard: Built-in zero-configuration GCP ingestion with instant log metrics and alerting policies.',
    SuccessorTech: 'Current Production Standard',
    MonthlyCostUSD: 340,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'Verified & Monitored (Native GCP)',
    AdoptionQuarter: '2024-Q1',
    DeprecationQuarter: 'Active',
    HealthScore: 96,
  },

  // --- 2. LEGACY AVAILABLE (PAST TECH, STILL HAVE ACCESS) ---
  {
    TechName: 'Supabase (PostgreSQL & Auth)',
    Category: 'Databases & Vector Storage',
    LifecycleStatus: 'Legacy Available',
    CurrentOrPastWorkload: 'Previously used for rapid MVP prototyping, user authentication tables, and client web testing in early 2024.',
    AccessStatus: 'Grandfathered Free Tier',
    WhyLostOrDeprecated: 'Why replaced: Migrated production to GCP Cloud SQL for VPC private networking and HIPAA/SOC2 compliance. Still available: Project is active on free tier with schema dumps and read-only query access.',
    SuccessorTech: 'PostgreSQL (Cloud SQL) & Custom Auth',
    MonthlyCostUSD: 0,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'Credentials Retained (Read-Only / Fallback)',
    AdoptionQuarter: '2023-Q3',
    DeprecationQuarter: '2024-Q2',
    HealthScore: 82,
  },
  {
    TechName: 'OpenAI API (GPT-4o / GPT-3.5)',
    Category: 'AI & LLM Orchestration',
    LifecycleStatus: 'Legacy Available',
    CurrentOrPastWorkload: 'Primary reasoning model for v1 product; now configured as a secondary fallback model in Agent Lab router if primary API fails.',
    AccessStatus: 'API Key Funded / On-Demand',
    WhyLostOrDeprecated: 'Why shifted: Gemini 2.5 offered 10x larger context window, 4x lower latency, and better cost efficiency. Still available: API key has active prepaid credit balance and functional integration code.',
    SuccessorTech: 'Gemini 2.5 Pro & Flash',
    MonthlyCostUSD: 85,
    TeamOwner: 'AI Engineering',
    CredentialsState: 'Credentials Retained (Emergency Fallback)',
    AdoptionQuarter: '2023-Q1',
    DeprecationQuarter: '2024-Q3',
    HealthScore: 88,
  },
  {
    TechName: 'Redis Cloud (Upstash / Redis Labs)',
    Category: 'Databases & Vector Storage',
    LifecycleStatus: 'Legacy Available',
    CurrentOrPastWorkload: 'Ephemeral session token storage and distributed rate limiting during initial multi-tenant launch.',
    AccessStatus: 'Grandfathered Free Tier',
    WhyLostOrDeprecated: 'Why shifted: Replaced with in-memory local caching and Cloud SQL unlogged tables. Still available: 30MB cluster remains alive and verified for quick cache benchmarking or testing.',
    SuccessorTech: 'Cloud Run In-Memory & Cloud SQL',
    MonthlyCostUSD: 0,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'Credentials Retained (Grandfathered)',
    AdoptionQuarter: '2023-Q4',
    DeprecationQuarter: '2024-Q3',
    HealthScore: 78,
  },
  {
    TechName: 'Vercel Pro',
    Category: 'Cloud & Compute Infrastructure',
    LifecycleStatus: 'Legacy Available',
    CurrentOrPastWorkload: 'Hosted early Next.js marketing landing pages and public documentation portal before container consolidation.',
    AccessStatus: 'Grandfathered Team Account',
    WhyLostOrDeprecated: 'Why shifted: Unified frontend deployments onto Google Cloud Run behind identical CDN/reverse-proxy infrastructure. Still available: Organization login active, DNS records ready if static failover needed.',
    SuccessorTech: 'Google Cloud Run + Nginx',
    MonthlyCostUSD: 20,
    TeamOwner: 'Product Eng',
    CredentialsState: 'Credentials Retained (Fallback Ready)',
    AdoptionQuarter: '2023-Q2',
    DeprecationQuarter: '2024-Q3',
    HealthScore: 85,
  },
  {
    TechName: 'Twilio SendGrid',
    Category: 'Customer & Revenue Ops',
    LifecycleStatus: 'Legacy Available',
    CurrentOrPastWorkload: 'Transactional emails, customer welcome onboarding, and password reset dispatches.',
    AccessStatus: 'Grandfathered Free Tier (100 emails/day)',
    WhyLostOrDeprecated: 'Why shifted: Reduced email volume by adopting in-app notifications and webhook pushes. Still available: Authenticated domain sender and API keys preserved for emergency batch announcements.',
    SuccessorTech: 'In-App Telemetry & Webhooks',
    MonthlyCostUSD: 0,
    TeamOwner: 'Product Eng',
    CredentialsState: 'Credentials Retained (Domain Verified)',
    AdoptionQuarter: '2023-Q2',
    DeprecationQuarter: '2024-Q4',
    HealthScore: 80,
  },
  {
    TechName: 'ChromaDB',
    Category: 'Databases & Vector Storage',
    LifecycleStatus: 'Legacy Available',
    CurrentOrPastWorkload: 'Local embedded vector similarity search used in early single-tenant offline proof-of-concepts.',
    AccessStatus: 'Open Source / Local Volume',
    WhyLostOrDeprecated: 'Why shifted: Required high RAM on containers without clustering support. Still available: Python/TS packages remain in development branch for offline mock evaluation.',
    SuccessorTech: 'pgvector on Cloud SQL',
    MonthlyCostUSD: 0,
    TeamOwner: 'AI Engineering',
    CredentialsState: 'Code Base Accessible (Offline Ready)',
    AdoptionQuarter: '2023-Q3',
    DeprecationQuarter: '2024-Q2',
    HealthScore: 75,
  },

  // --- 3. LOST ACCESS & DEPRECATED (PAST TECH, LOST & WHY) ---
  {
    TechName: 'Pinecone Vector DB',
    Category: 'Databases & Vector Storage',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Hosted serverless vector indexing for customer document retrieval and semantic search.',
    AccessStatus: 'Subscription Terminated / Account Closed',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: Vendor retired the free starter tier and imposed mandatory $70/month minimum base plan with aggressive index tiering fees. We chose not to renew because pgvector was already installed on our existing Postgres cluster at zero additional cost.',
    SuccessorTech: 'pgvector on Cloud SQL',
    MonthlyCostUSD: 0,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'No Active Access / Credentials Destroyed',
    AdoptionQuarter: '2023-Q3',
    DeprecationQuarter: '2024-Q2',
    HealthScore: 20,
  },
  {
    TechName: 'AWS ECS & Fargate',
    Category: 'Cloud & Compute Infrastructure',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Container cluster running background task queues and batch report generation.',
    AccessStatus: 'Account Decommissioned / Org Closed',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: Dedicated AWS organization account was terminated and decommissioned. Dual-cloud architecture created $4,200/month in idle NAT gateway and VPC peering overhead. Decommissioned to achieve single-pane-of-glass billing and IAM on GCP.',
    SuccessorTech: 'Google Cloud Run & Cloud Tasks',
    MonthlyCostUSD: 0,
    TeamOwner: 'Core Infrastructure',
    CredentialsState: 'No Active Access (AWS Account Closed)',
    AdoptionQuarter: '2023-Q1',
    DeprecationQuarter: '2024-Q1',
    HealthScore: 10,
  },
  {
    TechName: 'LangSmith (LangChain Tracing)',
    Category: 'Monitoring & Observability',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Visual LLM step debugging, prompt regression testing, and token latency diagnostics.',
    AccessStatus: 'Enterprise Pilot Expired',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: 90-day enterprise pilot expired and renewal quote was $1,500/month for seat licenses. Tracing history in the hosted cloud was locked to read-only after trial cutoff. Replaced by building native telemetry into Agent Lab with custom Cloud Logging.',
    SuccessorTech: 'Agent Lab Live Telemetry & OpenTelemetry',
    MonthlyCostUSD: 0,
    TeamOwner: 'AI Engineering',
    CredentialsState: 'Access Revoked (Trial Expired)',
    AdoptionQuarter: '2023-Q4',
    DeprecationQuarter: '2024-Q2',
    HealthScore: 15,
  },
  {
    TechName: 'Zapier Enterprise Automation',
    Category: 'Integrations & Automation',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Third-party trigger integration connecting CRM leads to Slack alerts and spreadsheet rows.',
    AccessStatus: 'Contract Terminated',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: Multi-seat annual contract terminated. Per-task pricing climbed steeply ($2,400/yr) during traffic spikes, and fragile multi-step zaps caused silent webhook drops. Replaced entirely with standardized MCP servers and native webhooks.',
    SuccessorTech: 'Model Context Protocol (MCP) & Webhooks',
    MonthlyCostUSD: 0,
    TeamOwner: 'Growth & Sales',
    CredentialsState: 'No Active Access (Subscription Canceled)',
    AdoptionQuarter: '2023-Q1',
    DeprecationQuarter: '2024-Q3',
    HealthScore: 25,
  },
  {
    TechName: 'Segment (Twilio Customer Data Platform)',
    Category: 'Customer & Revenue Ops',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Client-side event streaming, anonymous tracking, and SaaS tool marketing fan-out.',
    AccessStatus: 'Access Revoked / Sunset',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: Vendor phased out the developer tier and locked API event ingestion after reaching the 1,000 MTU limit. We opted not to sign a $12k annual enterprise contract, replacing it with direct first-party server logging to preserve user privacy.',
    SuccessorTech: 'First-Party Webhook Ingestion to Postgres',
    MonthlyCostUSD: 0,
    TeamOwner: 'Product Eng',
    CredentialsState: 'No Active Access (Workspace Deleted)',
    AdoptionQuarter: '2023-Q2',
    DeprecationQuarter: '2024-Q1',
    HealthScore: 15,
  },
  {
    TechName: 'Twitter / X Developer API (v2 Pro)',
    Category: 'Integrations & Automation',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Real-time social brand sentiment monitoring, developer alert broadcasting, and news keyword ingestion.',
    AccessStatus: 'Access Revoked / Sunset',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: Vendor eliminated free and affordable tiers overnight, raising the basic tier to $100/mo with severe caps and Pro tier to $5,000/mo. Developer application was suspended when legacy API v1.1 endpoints were shut down.',
    SuccessorTech: 'Brave Search API & RSS Feeds',
    MonthlyCostUSD: 0,
    TeamOwner: 'Growth & Sales',
    CredentialsState: 'API Tokens Invalidated by Vendor',
    AdoptionQuarter: '2023-Q1',
    DeprecationQuarter: '2023-Q4',
    HealthScore: 5,
  },
  {
    TechName: 'Auth0 (Okta)',
    Category: 'Customer & Revenue Ops',
    LifecycleStatus: 'Lost Access / Deprecated',
    CurrentOrPastWorkload: 'Hosted user login screen, social Google/GitHub OAuth redirects, and JWT signing.',
    AccessStatus: 'Account Decommissioned',
    WhyLostOrDeprecated: 'WHY ACCESS LOST: Reached active user threshold where custom domain and SAML SSO required enterprise tier jumping from $35/mo to $800/mo. Migrated to client-side Google Identity Services (GSI) and native session tokens.',
    SuccessorTech: 'Google Identity Services (GSI) & Session Tokens',
    MonthlyCostUSD: 0,
    TeamOwner: 'DevOps & Security',
    CredentialsState: 'No Active Access (Tenant Deleted)',
    AdoptionQuarter: '2023-Q2',
    DeprecationQuarter: '2024-Q1',
    HealthScore: 10,
  },
];

export const ALL_BRANDS = 'All Brands (Consolidated)';

export interface BrandMetadata {
  name: string;
  tagline: string;
  focus: string;
  badgeType?: string;
  keyAccounts?: string;
  domain?: string;
  logoUrl?: string;
  primaryColor: string;
  badgeBg: string;
  badgeBorder: string;
  badgeText: string;
}

export const URC_DEFAULT_LOGO = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none"><rect width="100" height="100" rx="20" fill="%230284c7"/><path d="M30 32v24c0 11 9 20 20 20s20-9 20-20V32" stroke="white" stroke-width="7" stroke-linecap="round"/><path d="M42 32h16c6 0 10 4 10 10s-4 10-10 10H42v16" stroke="%23bae6fd" stroke-width="5" stroke-linecap="round"/><circle cx="50" cy="52" r="4" fill="white"/></svg>';

export const FC_DEFAULT_LOGO = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none"><rect width="100" height="100" rx="20" fill="%2316a34a"/><path d="M26 68L46 48l12 12 22-26" stroke="white" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M64 34h16v16" stroke="white" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><circle cx="78" cy="34" r="4" fill="%23bbf7d0"/></svg>';

export const AL_DEFAULT_LOGO = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none"><rect width="100" height="100" rx="20" fill="%239333ea"/><circle cx="50" cy="50" r="14" fill="white"/><circle cx="50" cy="24" r="7" fill="%23e9d5ff"/><circle cx="74" cy="65" r="7" fill="%23e9d5ff"/><circle cx="26" cy="65" r="7" fill="%23e9d5ff"/><path d="M50 31v6M68 60l-6-4M32 60l6-4" stroke="white" stroke-width="4" stroke-linecap="round"/><circle cx="50" cy="50" r="6" fill="%239333ea"/></svg>';

export const BRAND_PROFILES: Record<string, BrandMetadata> = {
  'Uncle Robert Consulting': {
    name: 'Uncle Robert Consulting',
    tagline: 'Executive Strategy, Operations & M&A Advisory',
    focus: 'Enterprise Retainers, Due Diligence, Fractional CxO, Operating Holding',
    badgeType: 'Parent / Advisory',
    keyAccounts: 'OmniGlobal, Apex Capital, MedTech',
    domain: 'unclerobertconsulting.com',
    logoUrl: URC_DEFAULT_LOGO,
    primaryColor: '#0284c7', // Sky-600
    badgeBg: 'bg-sky-50 dark:bg-sky-950/40',
    badgeBorder: 'border-sky-300 dark:border-sky-800',
    badgeText: 'text-sky-700 dark:text-sky-300',
  },
  'Fundable Consulting': {
    name: 'Fundable Consulting',
    tagline: 'Startup Fundraising Readiness & Syndicate Placement',
    focus: 'Seed/Series A Pitch Decks, Financial Modeling, Investor Cohorts & Escrow Deals',
    badgeType: 'Venture & Capital',
    keyAccounts: 'Pitch Sprints, Syndicates, Cohorts',
    domain: 'fundableconsulting.com',
    logoUrl: FC_DEFAULT_LOGO,
    primaryColor: '#16a34a', // Green-600
    badgeBg: 'bg-emerald-50 dark:bg-emerald-950/40',
    badgeBorder: 'border-emerald-300 dark:border-emerald-800',
    badgeText: 'text-emerald-700 dark:text-emerald-300',
  },
  'Agent Lab': {
    name: 'Agent Lab',
    tagline: 'Autonomous AI Operating System & Enterprise Agent Fleet',
    focus: 'Agent Lab OS, Cloud Run Cluster, MCP Tooling, Client Portals, Fine-Tuning Hub',
    badgeType: 'AI Tech & SaaS',
    keyAccounts: 'Cloud Run, Gemini 2.5, MCP Fleet',
    domain: 'agentlab.ai',
    logoUrl: AL_DEFAULT_LOGO,
    primaryColor: '#9333ea', // Purple-600
    badgeBg: 'bg-purple-50 dark:bg-purple-950/40',
    badgeBorder: 'border-purple-300 dark:border-purple-800',
    badgeText: 'text-purple-700 dark:text-purple-300',
  },
};

export function createDataset(id: string, name: string, description: string, raw: Record<string, any>[]): Dataset {
  // Ensure every dataset has the Brand field populated
  const enrichedRaw = raw.map((item, idx) => {
    if (item.Brand) return item;
    if (id === 'sales-performance' || id === 'marketing-roi') {
      const brandsList: BrandName[] = ['Uncle Robert Consulting', 'Fundable Consulting', 'Agent Lab'];
      return { ...item, Brand: brandsList[idx % brandsList.length] };
    }
    if (id === 'tech-stack-lifecycle') {
      const brandsList: BrandName[] = ['Agent Lab', 'Uncle Robert Consulting', 'Fundable Consulting'];
      return { ...item, Brand: brandsList[idx % brandsList.length] };
    }
    // Default brand for agentlab telemetry, saas data, financial data without brand
    return { ...item, Brand: 'Agent Lab' };
  });

  const schema = inferSchema(enrichedRaw);
  const data = normalizeData(enrichedRaw, schema);
  return { id, name, description, data, schema };
}

export const sampleDatasets: Dataset[] = [
  createDataset(
    'tech-stack-lifecycle',
    'Tech Stack Architecture & Lifecycle Registry',
    'Comprehensive registry of technologies: current production tools, past tools still accessible with legacy access, and past tools with lost access (including detailed reasons, replacements, costs, and workloads).',
    rawTechStackData
  ),
  createDataset(
    'financial-board',
    'Financial Board & Cash Runway',
    'Executive financial control board: cash inflows vs outflows, vendor & compute costs, upcoming invoice due dates, active customer trial periods, and enterprise sales revenue.',
    rawFinancialData
  ),
  createDataset(
    'agentlab-telemetry',
    'Agent Lab SaaS Live Telemetry (Cloud Run)',
    'Live execution metrics from https://agentlab-718497644379.us-central1.run.app: latency, model tokens, tool calls, costs, and success rates.',
    rawAgentLabData
  ),
  createDataset(
    'web-portal-performance',
    'Websites, Landing Pages & Client Portals Performance',
    'Full performance tracking across public websites, conversion landing pages, developer docs, and authenticated client portals: bounce rate, LCP, page load speed, and client active usage.',
    rawWebPortalData
  ),
  createDataset(
    'hubspot-crm-deals',
    'HubSpot CRM Pipeline & Deal Conversion',
    'Live sync dataset from HubSpot CRM v3 API: deal stages, pipeline revenue, close duration, agent-associated runs, and HITL approvals.',
    rawHubspotDeals
  ),
  createDataset(
    'mcp-servers-telemetry',
    'Model Context Protocol (MCP) Server Telemetry',
    'Execution diagnostics across connected MCP servers (GitHub, PostgreSQL, HubSpot, Slack, Brave, Filesystem): tool calls, step depth, latency, and token footprint.',
    rawMcpTelemetry
  ),
  createDataset(
    'sales-performance',
    'Global Sales & Regional Revenue',
    'Multi-region monthly sales breakdown with revenue, profit margins, CAC, and satisfaction ratings.',
    rawSalesData
  ),
  createDataset(
    'saas-product-tiers',
    'SaaS Subscription & Growth Metrics',
    'Subscription tiers comparing ARR, active user counts, churn rate, Net Retention (NDR), and NPS.',
    rawSaasData
  ),
  createDataset(
    'marketing-roi',
    'Digital Marketing & Channel ROI',
    'Performance across ad networks comparing spend, impressions, conversion rates, and total return on investment.',
    rawMarketingData
  ),
];
